version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    build: ./producer
    volumes:
     - ./producer:/code
    depends_on: 
     - kafka
    links:
     - kafka
  consumer:
    build: ./consumer
    volumes:
     - ./consumer:/code
    depends_on: 
     - kafka
    links:
     - kafka